# Intro colab 


Importamos la libreria y verficamos la versión

In [7]:
import numpy as np
print(np.__version__)

1.21.6


creación de lista


In [8]:
mi_lista = [1, 2, 3, 4, 5, 6]
type(mi_lista)

list

In [10]:
mi_array = np.array(mi_lista)
display(
  type(mi_array),
  mi_array,
  mi_array.shape,
  mi_array.ndim
)

numpy.ndarray

array([1, 2, 3, 4, 5, 6])

(6,)

1

In [11]:
mi_array_dato = np.array(48)
display(
  type(mi_array_dato),
  mi_array_dato,
  mi_array_dato.shape,
  mi_array_dato.ndim
)

numpy.ndarray

array(48)

()

0

In [13]:
mi_matriz = np.array((mi_lista, mi_lista))
display(
  type(mi_matriz),
  mi_matriz,
  mi_matriz.shape,
  mi_matriz.ndim
)

numpy.ndarray

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

(2, 6)

2

In [14]:
mi_matriz_3d = np.array([[mi_lista, mi_lista],[mi_lista, mi_lista]])
display(
  type(mi_matriz_3d),
  mi_matriz_3d,
  mi_matriz_3d.shape,
  mi_matriz_3d.ndim
)

numpy.ndarray

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]])

(2, 2, 6)

3

In [16]:
mi_matriz_n = np.array(mi_lista, ndmin=5)
display(
  type(mi_matriz_n),
  mi_matriz_n,
  mi_matriz_n.shape,
  mi_matriz_n.ndim
)

numpy.ndarray

array([[[[[1, 2, 3, 4, 5, 6]]]]])

(1, 1, 1, 1, 6)

5

In [17]:
mis_ceros = np.zeros(5)
mis_ceros


array([0., 0., 0., 0., 0.])

In [18]:
mis_unos = np.ones(3)
mis_unos

array([1., 1., 1.])

In [19]:
mi_rango = np.arange(10)
mi_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
mi_linspace = np.linspace(
    start=1,
    stop=5,
    num=10,
    endpoint=True
)
mi_linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
mis_aleatorios_1 = np.random.random(size=(5,3))
mis_aleatorios_1

array([[0.25273363, 0.77181288, 0.87004221],
       [0.78475099, 0.70185905, 0.13545108],
       [0.18435947, 0.55422084, 0.92238059],
       [0.49818364, 0.45061967, 0.53060187],
       [0.1696677 , 0.97146657, 0.96088878]])

In [28]:
mis_aleatorios_2 = np.random.normal(
    loc=1,
    scale=2,
    size=(5,5)
)
mis_aleatorios_2

array([[-1.0624809 ,  2.92588754,  1.50911327, -0.77993455,  3.51064278],
       [ 2.54375305, -3.81985824,  0.55274723,  0.24671432, -0.55946726],
       [-0.97667993,  1.38970337, -1.13419311,  2.59061404,  1.7092851 ],
       [-1.57649837, -3.20259759, -0.02030079, -1.46807758,  0.41212697],
       [ 0.09076385,  0.44814535,  1.02250435, -1.27144341, -0.41381333]])

In [29]:
mis_aleatorios_3 = np.random.uniform(
    low=1,
    high=10,
    size=(5,5)
)
mis_aleatorios_3

array([[4.13750778, 5.462673  , 6.6362735 , 1.38721972, 2.16358156],
       [7.21781082, 2.5885827 , 7.36374478, 8.86931014, 4.47875507],
       [8.82834116, 6.68140215, 1.21837229, 4.19417184, 8.13977182],
       [8.25186026, 7.35010554, 1.13776469, 5.04024404, 9.33286086],
       [2.25711941, 2.79392575, 4.57419049, 8.19542071, 1.35780399]])

In [33]:
display(
    mi_array,
    mi_array[0],
    mi_array[2: 4],
    mi_array[:-2]
)

array([1, 2, 3, 4, 5, 6])

1

array([3, 4])

array([1, 2, 3, 4])

In [34]:
mi_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
mi_array

array([1, 2, 3, 4, 5, 6])

In [38]:
a = np.array([1,2,3])
b = np.array([11,12,13])
ab = np.column_stack((a,b))
display(
    a,
    b,
    ab
)

array([1, 2, 3])

array([11, 12, 13])

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [42]:
base = np.random.random(size=15)
base *= 100
display(
  base,
  np.mean(base),
  np.median(base),
  np.sum(base),
  np.var(base),
  np.std(base)
)


array([ 6.03536731, 74.98811441, 35.9948419 , 28.04748543,  8.14201123,
       43.51619785, 11.99942812,  2.02186441, 34.03137665, 48.44303572,
       47.17131399, 92.29926765, 14.19537344,  8.05087253, 88.12278678])

36.203955828303336

34.03137665240854

543.05933742455

831.3442345070335

28.833040673973905

In [46]:
ma = np.random.random(size=(5,5))
mb = np.random.random(size=(5,5))
ma + mb

array([[1.17798752, 1.11180856, 1.20850267, 0.89735732, 1.80402801],
       [0.64576386, 0.92645461, 1.2167116 , 0.93903104, 1.108284  ],
       [0.66344527, 0.77005885, 0.92644869, 1.39655477, 1.23084332],
       [1.21297335, 0.79832763, 0.71241766, 1.25423486, 1.52985132],
       [1.07883902, 1.36850581, 0.85943393, 0.32225585, 1.27262726]])

In [47]:
np.arange(10) > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
np.random.random(size=(10)) > 0.5

array([ True, False,  True, False,  True, False,  True,  True,  True,
       False])

In [55]:
ba = np.random.random(size=(10)) > 0.5
bb = np.random.random(size=(10)) > 0.5
display(
    ba,
    bb,
    np.logical_and(ba, bb)
)

array([False, False, False, False,  True,  True, False,  True,  True,
       False])

array([ True,  True, False, False, False,  True,  True,  True, False,
       False])

array([False, False, False, False, False,  True, False,  True, False,
       False])

In [57]:
for e in mi_array:
  print(e)

1
2
3
4
5
6


In [58]:
for e in mi_matriz:
  print(e)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [60]:
for e in np.nditer(mi_matriz):
  print(e)
  

1
2
3
4
5
6
1
2
3
4
5
6
